apiVersion: v1
kind: Service
metadata:
  name: demo-service
spec:
  type: LoadBalancer                 # AWS will create a Load Balancer
  selector:
    app: demo                        # Targets pods with this label
  ports:
  - port: 80                         # Public port
    targetPort: 80                   # Pod port
    protocol: TCP                    # Protocol used